name: Run tests

on: [push]

jobs:
  run_tests_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache JavaFX SDK
        uses: actions/cache@v3
        with:
          path: |
            javafx-sdk
          key: javafx-sdk-22
          restore-keys: |
            javafx-sdk-22

      - name: Download and setup JavaFX
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://download2.gluonhq.com/openjfx/22/openjfx-22_linux-aarch64_bin-sdk.zip -O javafx-sdk.zip
          unzip -o javafx-sdk.zip -d javafx-sdk
          echo "JAVAFX_SDK_PATH=$PWD/javafx-sdk" >> $GITHUB_ENV

      - name: Run tests script with JavaFX
        run: |
          ./run_tests.sh
        working-directory: ./scripts/run_tests
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-path }}
          PATH: ${{ steps.setup-java.outputs.java-path }}/bin:$PATH
          JAVAFX_SDK_PATH: ${{ env.JAVAFX_SDK_PATH }}
